name: my_website
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
     sdk: flutter
  flutter_svg: ^2.0.17
  jaspr: ^0.18.0
  jaspr_flutter_embed: ^0.4.5
  jaspr_router: ^0.6.3

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.1
  jaspr_builder: ^0.18.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jaspr_lints: ^0.3.1

jaspr:
  mode: static

flutter:
  uses-material-design: true
